version: '3.1'

services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    working_dir: /app
    volumes:
      - ./app:/app
    command: python app.py

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
